cp -r ~/.config/ags .
cp -r ~/.config/btop .
cp -r ~/.config/code-flags.conf .
cp -r ~/.config/electron-flags.conf .
cp -r ~/.config/hypr .
cp -r ~/.config/kitty .
cp -r ~/.config/neofetch .
cp -r ~/.config/rofi .
cp -r ~/.config/spotify-flags.conf .
cp -r ~/.config/swaylock .
cp -r ~/.config/waybar .
cp -r ~/.config/WebCord-flags.conf .
